import type { CalendarEvent, ReminderItem, TaskItem } from '@/types/assistant';
import { daysAgoIso, daysFromNowIso, todayIso } from '@/utils/date-utils';

export const INITIAL_TASKS: TaskItem[] = [
  {
    id: 'presentation',
    title: 'Presentación cliente',
    description: 'Entregar presentación final al cliente',
    dueLabel: 'Hoy, 3:00 PM',
    dueDate: 'today',
    scheduledAt: todayIso(),
    createdAt: daysAgoIso(2),
    estimatedMinutes: 120,
    priority: 'high',
    status: 'pending',
    category: 'Trabajo',
    tags: ['cliente', 'urgente'],
  },
  {
    id: 'medicine',
    title: 'Comprar medicamentos',
    dueLabel: 'Hoy, 6:00 PM',
    dueDate: 'today',
    scheduledAt: todayIso(),
    createdAt: daysAgoIso(1),
    estimatedMinutes: 30,
    priority: 'high',
    status: 'pending',
    category: 'Salud',
    tags: ['personal'],
  },
  {
    id: 'invoice',
    title: 'Pagar factura de internet',
    dueLabel: 'Mañana, 10:00 AM',
    dueDate: 'tomorrow',
    scheduledAt: daysFromNowIso(1),
    createdAt: daysAgoIso(3),
    estimatedMinutes: 15,
    priority: 'high',
    status: 'pending',
    category: 'Personal',
    tags: ['finanzas'],
  },
  {
    id: 'meeting',
    title: 'Preparar reunión semanal',
    dueLabel: 'Viernes, 9:00 AM',
    scheduledAt: daysFromNowIso(3),
    createdAt: daysAgoIso(5),
    estimatedMinutes: 60,
    priority: 'medium',
    status: 'pending',
    category: 'Trabajo',
    tags: ['equipo'],
  },
  {
    id: 'report',
    title: 'Informe mensual',
    dueLabel: 'Lunes, 5:00 PM',
    scheduledAt: daysFromNowIso(5),
    createdAt: daysAgoIso(7),
    estimatedMinutes: 90,
    priority: 'medium',
    status: 'pending',
    category: 'Trabajo',
    tags: ['informe'],
  },
  {
    id: 'gym',
    title: 'Ir al gimnasio',
    dueLabel: 'Ayer',
    scheduledAt: daysAgoIso(1),
    createdAt: daysAgoIso(2),
    completedAt: daysAgoIso(1),
    estimatedMinutes: 60,
    actualMinutes: 55,
    priority: 'low',
    status: 'completed',
    category: 'Salud',
    tags: ['personal'],
  },
  {
    id: 'taxes-q1',
    title: 'Declaración de impuestos Q1',
    scheduledAt: daysAgoIso(45),
    createdAt: daysAgoIso(60),
    completedAt: daysAgoIso(44),
    estimatedMinutes: 180,
    actualMinutes: 240,
    priority: 'high',
    status: 'completed',
    category: 'Personal',
    tags: ['finanzas', 'trimestral'],
  },
  {
    id: 'client-onboarding',
    title: 'Onboarding cliente Acme',
    scheduledAt: daysAgoIso(12),
    createdAt: daysAgoIso(20),
    completedAt: daysAgoIso(11),
    estimatedMinutes: 120,
    actualMinutes: 95,
    priority: 'high',
    status: 'completed',
    category: 'Trabajo',
    tags: ['cliente'],
  },
  {
    id: 'weekly-review',
    title: 'Revisión semanal del equipo',
    scheduledAt: daysAgoIso(7),
    createdAt: daysAgoIso(14),
    completedAt: daysAgoIso(7),
    estimatedMinutes: 45,
    actualMinutes: 50,
    priority: 'medium',
    status: 'completed',
    category: 'Trabajo',
    tags: ['equipo', 'recurrente'],
  },
  {
    id: 'grocery',
    title: 'Compras del supermercado',
    scheduledAt: daysAgoIso(3),
    createdAt: daysAgoIso(4),
    completedAt: daysAgoIso(3),
    estimatedMinutes: 40,
    actualMinutes: 65,
    priority: 'low',
    status: 'completed',
    category: 'Compras',
    tags: ['personal'],
  },
  {
    id: 'course-module',
    title: 'Módulo 4 del curso de React',
    scheduledAt: daysAgoIso(30),
    createdAt: daysAgoIso(45),
    completedAt: daysAgoIso(28),
    estimatedMinutes: 90,
    actualMinutes: 110,
    priority: 'medium',
    status: 'completed',
    category: 'Estudios',
    tags: ['curso'],
  },
  {
    id: 'dentist',
    title: 'Cita con el dentista',
    scheduledAt: daysAgoIso(90),
    createdAt: daysAgoIso(100),
    completedAt: daysAgoIso(90),
    estimatedMinutes: 60,
    actualMinutes: 75,
    priority: 'medium',
    status: 'completed',
    category: 'Salud',
    tags: ['personal'],
  },
  {
    id: 'annual-review',
    title: 'Evaluación anual de desempeño',
    scheduledAt: daysAgoIso(200),
    createdAt: daysAgoIso(220),
    completedAt: daysAgoIso(198),
    estimatedMinutes: 120,
    actualMinutes: 150,
    priority: 'high',
    status: 'completed',
    category: 'Trabajo',
    tags: ['anual'],
  },
  {
    id: 'monday-planning',
    title: 'Planificación del lunes',
    scheduledAt: daysAgoIso(14),
    createdAt: daysAgoIso(15),
    completedAt: daysAgoIso(14),
    estimatedMinutes: 30,
    actualMinutes: 35,
    priority: 'medium',
    status: 'completed',
    category: 'Trabajo',
    tags: ['recurrente'],
  },
  {
    id: 'monday-planning-2',
    title: 'Planificación del lunes',
    scheduledAt: daysAgoIso(21),
    createdAt: daysAgoIso(22),
    completedAt: daysAgoIso(21),
    estimatedMinutes: 30,
    actualMinutes: 28,
    priority: 'medium',
    status: 'completed',
    category: 'Trabajo',
    tags: ['recurrente'],
  },
];

export const INITIAL_EVENTS: CalendarEvent[] = [
  {
    id: 'meeting-1',
    title: 'Reunión de equipo',
    date: 'today',
    scheduledAt: todayIso(),
    time: '2:00 PM',
    type: 'meeting',
    location: 'Sala virtual',
  },
  {
    id: 'meeting-2',
    title: 'Presentación cliente',
    date: 'today',
    scheduledAt: todayIso(),
    time: '3:00 PM',
    type: 'meeting',
  },
  {
    id: 'meeting-3',
    title: 'Sync con diseño',
    date: 'today',
    scheduledAt: todayIso(),
    time: '5:30 PM',
    type: 'meeting',
  },
  {
    id: 'meeting-4',
    title: 'Revisión de sprint',
    date: 'tomorrow',
    scheduledAt: daysFromNowIso(1),
    time: '10:00 AM',
    type: 'meeting',
  },
  {
    id: 'event-1',
    title: 'Cumpleaños de Ana',
    date: 'tomorrow',
    scheduledAt: daysFromNowIso(1),
    time: 'Todo el día',
    type: 'event',
  },
  {
    id: 'event-past-1',
    title: 'Workshop de producto',
    date: 'past',
    scheduledAt: daysAgoIso(60),
    time: '9:00 AM',
    type: 'meeting',
  },
  {
    id: 'event-past-2',
    title: 'Reunión con inversores',
    date: 'past',
    scheduledAt: daysAgoIso(120),
    time: '4:00 PM',
    type: 'meeting',
  },
];

export const INITIAL_REMINDERS: ReminderItem[] = [
  { id: 'r1', title: 'Llamar a Carlos', timeLabel: 'Al salir del trabajo' },
  { id: 'r2', title: 'Comprar café', timeLabel: 'Esta tarde' },
  { id: 'r3', title: 'Enviar factura', timeLabel: 'Antes de las 5 PM' },
];

export const PRIORITY_LABELS: Record<string, string> = {
  high: 'Alta',
  medium: 'Media',
  low: 'Baja',
};

export const REPORT_PRESET_LABELS = {
  week: 'Semanal',
  month: 'Mensual',
  quarter: 'Trimestral',
  year: 'Anual',
  custom: 'Rango personalizado',
} as const;
